<template>
  <div class="app-frame">
    <aside class="sidebar" :class="{ open: menuOpen }">
      <div class="wordmark"><span class="mark">P</span><span>ProofLine</span><small>application workspace</small></div>
      <p class="demo-tag">Fictional interactive demo</p>
      <nav aria-label="ProofLine demo navigation">
        <p class="nav-label">Find work</p>
        <button v-for="item in primaryNav" :key="item.id" :class="{ active: screen === item.id }" @click="go(item.id)"><span>{{ item.icon }}</span>{{ item.label }}</button>
        <p class="nav-label">Apply</p>
        <button v-for="item in applyNav" :key="item.id" :class="{ active: screen === item.id }" @click="go(item.id)"><span>{{ item.icon }}</span>{{ item.label }}</button>
        <p class="nav-label">My setup</p>
        <button v-for="item in setupNav" :key="item.id" :class="{ active: screen === item.id }" @click="go(item.id)"><span>{{ item.icon }}</span>{{ item.label }}</button>
      </nav>
      <button class="reset" @click="resetDemo">↺ Reset fictional demo</button>
    </aside>
    <div class="app-main">
      <header class="topbar"><button class="mobile-menu" @click="menuOpen = !menuOpen">☰</button><div><strong>Sascha Linden</strong><span>{{ fixture.candidate.target }}</span></div><div class="header-status"><i></i> Browser-only demo</div></header>
      <main>
        <div class="demo-notice"><strong>Illustrative workspace.</strong> {{ fixture.notice }}</div>

        <section v-if="screen === 'today'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Today</p><h1>Your application workspace</h1><p>See what needs a decision, prepare a reviewed application, and keep the next step visible.</p></div><button class="primary" @click="runScan">{{ scanning ? 'Refreshing opportunities…' : '↻ Simulate opportunity refresh' }}</button></div>
          <div class="stats"><article><span>Opportunities to review</span><strong>{{ reviewJobs.length }}</strong><button @click="go('jobs')">Open queue →</button></article><article><span>Application packs in progress</span><strong>{{ activeApplications.length }}</strong><button @click="go('packs')">Open studio →</button></article><article><span>Evidence ready to use</span><strong>{{ fixture.candidate.evidence.filter(item => item.status !== 'Set').length }}</strong><button @click="go('profile')">View profile →</button></article><article><span>Next review</span><strong class="small-stat">Aurora Relay</strong><button @click="selectJob('aurora-platform'); go('readiness')">Check readiness →</button></article></div>
          <div class="two-columns"><section class="panel"><div class="panel-title"><div><p class="eyebrow">Recommended next step</p><h2>Review Aurora Relay before composing</h2></div><span class="score-pill">{{ selectedJob.score }}/100 fit</span></div><p>{{ selectedJob.summary }}</p><ul class="check-list"><li v-for="signal in selectedJob.signals" :key="signal">{{ signal }}</li></ul><div class="actions"><button class="primary" @click="selectJob('aurora-platform'); go('readiness')">Open readiness review</button><button class="secondary" @click="selectJob('aurora-platform'); go('jobs')">View opportunity</button></div></section><section class="panel flow-panel"><p class="eyebrow">How the workflow works</p><h2>Evidence first, then human review</h2><ol><li><b>1</b> Collect and compare opportunities</li><li><b>2</b> Make the fit and gaps visible</li><li><b>3</b> Assemble an evidence-led draft</li><li><b>4</b> Review before any submission</li></ol></section></div>
          <section class="panel"><p class="eyebrow">Recent activity</p><h2>Demo activity feed</h2><div class="activity"><p><b>Today</b><span>Illustrative opportunity refresh prepared three fictional roles for review.</span></p><p><b>Today</b><span>Architecture evidence is ready for the Aurora Relay draft.</span></p><p><b>Yesterday</b><span>Harborlight Works was saved for a later decision.</span></p></div></section>
        </section>

        <section v-else-if="screen === 'leads'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Leads</p><h1>Capture an opportunity before it is ready to review</h1><p>In the product, a lead can come from a referral, a company page, or your own research. This demo resolves only fictional examples.</p></div></div>
          <div class="two-columns"><section class="panel"><p class="eyebrow">Add a fictional lead</p><h2>Turn a note into a reviewable opportunity</h2><label class="field-label">Lead note or example URL<textarea v-model="leadDraft" rows="5" placeholder="For example: fictional referral to a platform leadership role" /></label><div class="actions"><button class="primary" @click="resolveLead">Simulate resolve & score</button><button class="secondary" @click="leadDraft = ''">Clear</button></div><p v-if="leadMessage" class="success">{{ leadMessage }}</p></section><section class="panel"><p class="eyebrow">What happens next</p><h2>Evidence-aware triage</h2><ol class="simple-steps"><li>Capture the opportunity and its source.</li><li>Compare it to the fictional target profile.</li><li>Make the score, evidence, and open questions visible.</li><li>Send it to Top Jobs for a human decision.</li></ol></section></div>
          <section class="panel no-pad"><div v-for="lead in leads" :key="lead.id" class="evidence-row"><span class="file-icon">⌁</span><div><strong>{{ lead.company }} · {{ lead.title }}</strong><span>{{ lead.detail }}</span></div><b :class="['status', lead.status]">{{ lead.status === 'review' ? 'Ready to review' : 'New lead' }}</b></div></section>
        </section>

        <section v-else-if="screen === 'jobs'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Opportunity inbox</p><h1>Review top opportunities</h1><p>Scores are transparent illustrative signals—not predictions or automated decisions.</p></div></div>
          <section class="panel no-pad"><div class="job-row header-row"><span>Opportunity</span><span>Fit signal</span><span>Decision</span></div><article v-for="job in jobs" :key="job.id" class="job-row"><div><strong>{{ job.company }}</strong><span>{{ job.title }} · {{ job.location }}</span><small>{{ job.source }} · {{ job.salary }}</small></div><div><b class="fit" :class="fitClass(job.score)">{{ job.score }}</b><span class="muted">{{ job.signals.slice(0, 2).join(' · ') }}</span></div><div class="decision"><span :class="['status', job.status]">{{ statusLabel(job.status) }}</span><button class="secondary small" @click="selectJob(job.id); expandedJob = expandedJob === job.id ? '' : job.id">{{ expandedJob === job.id ? 'Close' : 'Review' }}</button></div><div v-if="expandedJob === job.id" class="job-detail"><div><p>{{ job.summary }}</p><p><strong>Why it may fit</strong></p><ul><li v-for="signal in job.signals" :key="signal">{{ signal }}</li></ul></div><div><p><strong>Review point</strong></p><p>{{ job.gap }}</p><div class="actions"><button class="primary" @click="setDecision(job, 'apply')">Prepare application</button><button class="secondary" @click="setDecision(job, 'saved')">Save for later</button><button class="ghost" @click="setDecision(job, 'dismissed')">Not now</button></div></div></div></article></section>
        </section>

        <section v-else-if="screen === 'packs'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Pack studio</p><h1>Build a reviewable application pack</h1><p>Every claim is tied to fictional evidence and stays editable.</p></div><button class="secondary" @click="go('jobs')">Choose another role</button></div>
          <div class="studio"><section class="panel"><p class="eyebrow">Selected opportunity</p><h2>{{ selectedJob.company }} · {{ selectedJob.title }}</h2><p>{{ selectedJob.summary }}</p><div class="score-line"><b :class="['fit', fitClass(selectedJob.score)]">{{ selectedJob.score }}</b><span>Illustrative fit score</span></div><hr><p class="eyebrow">Pack contents</p><button v-for="part in packParts" :key="part" :class="['studio-part', { selected: selectedPart === part }]" @click="selectedPart = part">{{ part }} <span>Ready</span></button></section><section class="panel compose"><p class="eyebrow">{{ selectedPart }}</p><h2>{{ selectedJob.pack.title }}</h2><p class="callout">{{ selectedJob.pack.intro }}</p><label>Opening direction<textarea v-model="draftOpening" rows="3" /></label><p class="eyebrow">Evidence-backed claims</p><label v-for="(claim, index) in editableClaims" :key="index" class="claim"><input v-model="enabledClaims" type="checkbox" :value="index"><span>{{ claim }}</span></label><label>Conversation to have before applying<textarea v-model="draftQuestion" rows="2" /></label><div class="actions"><button class="primary" @click="saveDraft">Save illustrative draft</button><button class="secondary" @click="go('readiness')">Review readiness →</button></div><p v-if="draftSaved" class="success">✓ Draft updated locally in this browser session.</p></section></div>
        </section>

        <section v-else-if="screen === 'compose'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Compose</p><h1>Keep the application editable and reviewable</h1><p>The draft below is prepared from invented evidence. No document is generated, sent, or stored.</p></div><button class="secondary" @click="go('packs')">← Back to Pack Studio</button></div>
          <div class="studio"><section class="panel"><p class="eyebrow">Application pack</p><h2>{{ selectedJob.company }}</h2><p>{{ selectedJob.title }}</p><div class="score-line"><b :class="['fit', fitClass(selectedJob.score)]">{{ selectedJob.score }}</b><span>Illustrative fit score</span></div><hr><p><strong>Included evidence</strong></p><ul class="check-list"><li v-for="claim in editableClaims" :key="claim">{{ claim }}</li></ul><button class="secondary" @click="go('readiness')">Open readiness review</button></section><section class="panel compose"><p class="eyebrow">Recruiter message</p><h2>Human-edited application draft</h2><label>Subject line<input v-model="composeSubject" /></label><label>Message<textarea v-model="composeMessage" rows="10" /></label><div class="actions"><button class="primary" @click="composeReviewed = true">Mark ready for human review</button><button class="secondary" @click="go('track')">Open submission checklist →</button></div><p v-if="composeReviewed" class="success">✓ The fictional draft is ready for a human to review. This demo cannot submit it.</p></section></div>
        </section>

        <section v-else-if="screen === 'readiness'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Application readiness</p><h1>Review before you compose or submit</h1><p>ProofLine makes the supporting evidence, open questions, and human review point explicit.</p></div></div>
          <div class="readiness-layout"><section class="panel readiness-score"><p class="eyebrow">Readiness for {{ selectedJob.company }}</p><strong>{{ readinessScore }}</strong><span>/100</span><p>{{ readinessScore >= 80 ? 'Ready for human review' : 'A few checks still need attention' }}</p><div class="meter"><i :style="{ width: `${readinessScore}%` }"></i></div></section><section class="panel"><p class="eyebrow">Review checklist</p><h2>Confirm what goes into the draft</h2><label v-for="item in readinessChecks" :key="item.id" class="check-row"><input v-model="checkedReadiness" type="checkbox" :value="item.id"><span><b>{{ item.title }}</b><small>{{ item.detail }}</small></span></label><button class="primary" @click="go('packs')">Return to Pack Studio</button></section></div>
          <section class="panel"><p class="eyebrow">Transparent fit explanation</p><h2>What drives the illustrative {{ selectedJob.score }} score</h2><div class="explanation"><div><b>48</b><span>Starting point</span></div><div><b>+{{ selectedJob.signals.length * 12 }}</b><span>Role signals matched</span></div><div><b>- 4</b><span>Open review point</span></div><div><b>= {{ selectedJob.score }}</b><span>Illustrative result</span></div></div><p class="callout">{{ selectedJob.gap }} A person must decide whether and how to address it.</p></section>
        </section>

        <section v-else-if="screen === 'track'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Submit & track</p><h1>Keep the next human step clear</h1><p>This demo never submits applications. It shows how a reviewed application can be tracked.</p></div></div>
          <section class="panel no-pad"><div v-for="application in applications" :key="application.jobId" class="track-row"><div><strong>{{ jobFor(application.jobId).company }}</strong><span>{{ jobFor(application.jobId).title }}</span></div><div><span class="status apply">{{ application.stage }}</span><small>Updated {{ application.updated }}</small></div><div><p><b>Next:</b> {{ application.next }}</p><button class="secondary small" @click="advanceApplication(application)">Advance demo stage</button></div></div></section>
        </section>

        <section v-else-if="screen === 'activity'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Activity report</p><h1>See the application story, not just the status</h1><p>Every event is fictional and stays in this browser session.</p></div></div>
          <section class="panel"><p class="eyebrow">Application timeline</p><h2>{{ selectedJob.company }} · {{ selectedJob.title }}</h2><div class="timeline"><article v-for="event in activity" :key="event.id"><i></i><div><strong>{{ event.title }}</strong><span>{{ event.when }} · {{ event.detail }}</span></div></article></div><button class="secondary" @click="addActivity">Simulate a review event</button></section>
        </section>

        <section v-else-if="screen === 'setup'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Materials & setup</p><h1>Prepare evidence before looking for work</h1><p>This fictional setup flow shows how a profile can be shaped from material without uploading anything in the public demo.</p></div><button class="primary" @click="analyzeMaterials">{{ materialsAnalyzed ? 'Fictional analysis complete' : 'Simulate material analysis' }}</button></div>
          <div class="two-columns"><section class="panel"><p class="eyebrow">Fictional materials</p><h2>What a private workspace would review</h2><div class="material-card" v-for="item in materials" :key="item.name"><span>▤</span><div><strong>{{ item.name }}</strong><small>{{ item.detail }}</small></div><b>{{ item.status }}</b></div></section><section class="panel"><p class="eyebrow">Profile recommendations</p><h2>Review, then decide</h2><div v-if="materialsAnalyzed" class="recommendations"><label v-for="recommendation in recommendations" :key="recommendation" class="claim"><input v-model="approvedRecommendations" type="checkbox" :value="recommendation"><span>{{ recommendation }}</span></label></div><p v-else class="callout">Run the simulated analysis to reveal fictional role and evidence recommendations. In the real product, a person reviews each one.</p><button class="secondary" :disabled="!materialsAnalyzed" @click="go('profile')">Open profile & evidence →</button></section></div>
        </section>

        <section v-else-if="screen === 'profile'" class="page">
          <div class="page-heading"><div><p class="eyebrow">Profile & evidence</p><h1>Keep claims connected to evidence</h1><p>All material below is fictional and exists only inside this demo.</p></div><button class="secondary" @click="evidenceMessage = 'In the public demo, adding material is simulated—nothing leaves your browser.'">+ Simulate adding evidence</button></div><p v-if="evidenceMessage" class="success">{{ evidenceMessage }}</p><div class="profile-grid"><section class="panel"><p class="eyebrow">Candidate profile</p><h2>{{ fixture.candidate.displayName }}</h2><p>{{ fixture.candidate.headline }} · {{ fixture.candidate.location }}</p><p><strong>Target:</strong> {{ fixture.candidate.target }}</p><div class="chips"><span v-for="strength in fixture.candidate.strengths" :key="strength">{{ strength }}</span></div></section><section class="panel"><p class="eyebrow">Evidence status</p><h2>Ready for review</h2><p>3 evidence items are ready. Each remains subject to human review before use.</p><button class="primary" @click="selectJob('aurora-platform'); go('packs')">Use evidence in a pack →</button></section></div><section class="panel no-pad"><div v-for="item in fixture.candidate.evidence" :key="item.name" class="evidence-row"><span class="file-icon">▤</span><div><strong>{{ item.name }}</strong><span>{{ item.type }} · {{ item.detail }}</span></div><b class="ready">{{ item.status }}</b></div></section>
        </section>

        <section v-else-if="screen === 'sources'" class="page"><div class="page-heading"><div><p class="eyebrow">Sources</p><h1>Control where opportunities come from</h1><p>These are fictional source examples. The public demo never contacts a website or scans a feed.</p></div></div><section class="panel no-pad"><div v-for="source in sources" :key="source.id" class="track-row"><div><strong>{{ source.name }}</strong><span>{{ source.type }} · {{ source.description }}</span></div><div><span :class="['status', source.enabled ? 'apply' : 'saved']">{{ source.enabled ? 'Included' : 'Paused' }}</span></div><div><button class="secondary small" @click="source.enabled = !source.enabled">{{ source.enabled ? 'Pause in demo' : 'Include in demo' }}</button></div></div></section></section>

        <section v-else class="page"><div class="page-heading"><div><p class="eyebrow">Demo settings</p><h1>Safe by design</h1><p>This published demo has no account, backend, AI call, upload, tracking, or submission capability.</p></div></div><section class="panel settings"><label><span>Browser-only mode</span><input type="checkbox" checked disabled></label><label><span>Fictional fixture data</span><input type="checkbox" checked disabled></label><label><span>Human review required</span><input type="checkbox" checked disabled></label><button class="secondary" @click="resetDemo">Reset the demonstration state</button></section></section>
      </main>
    </div>
    <div v-if="toast" class="toast" role="status">{{ toast }}</div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import fixture from './demo-data/proofline-public-demo.json'

const primaryNav = [{ id: 'today', label: 'Today', icon: '⌂' }, { id: 'leads', label: 'Leads', icon: '⌁' }, { id: 'jobs', label: 'Top jobs', icon: '▤' }]
const applyNav = [{ id: 'packs', label: 'Pack Studio', icon: '▣' }, { id: 'compose', label: 'Compose', icon: '✎' }, { id: 'readiness', label: 'Readiness', icon: '◔' }, { id: 'track', label: 'Submit & track', icon: '↗' }, { id: 'activity', label: 'Activity report', icon: '◷' }]
const setupNav = [{ id: 'setup', label: 'Materials & setup', icon: '▧' }, { id: 'profile', label: 'Profile & evidence', icon: '◉' }, { id: 'sources', label: 'Sources', icon: '⌘' }, { id: 'settings', label: 'Settings', icon: '⚙' }]
const originalJobs = JSON.parse(JSON.stringify(fixture.jobs))
const screen = ref('today'), menuOpen = ref(false), jobs = ref(JSON.parse(JSON.stringify(fixture.jobs))), selectedId = ref('aurora-platform'), expandedJob = ref(''), scanning = ref(false), toast = ref(''), selectedPart = ref('Application outline'), draftSaved = ref(false), evidenceMessage = ref('')
const applications = ref(JSON.parse(JSON.stringify(fixture.applications)))
const enabledClaims = ref([0, 1, 2]), checkedReadiness = ref(['evidence', 'gap']), draftOpening = ref('Connect platform architecture decisions to clear delivery outcomes.'), draftQuestion = ref('')
const leads = ref([{ id: 'northern-council', company: 'Northern Council', title: 'Integration Strategy Lead', detail: 'Fictional referral lead · awaiting initial review', status: 'new' }, { id: 'meridian', company: 'Meridian Loop', title: 'Enterprise Platform Architect', detail: 'Fictional company-page lead · score explanation prepared', status: 'review' }])
const leadDraft = ref(''), leadMessage = ref(''), composeReviewed = ref(false), composeSubject = ref('Platform Architecture Lead — evidence-led application'), composeMessage = ref('Hello Aurora Relay team,\n\nI am interested in the Platform Architecture Lead role. My fictional evidence pack highlights platform direction, integration strategy, and cross-team technical leadership.\n\nI would welcome a conversation about how platform and product teams share operational ownership.'), activity = ref([{ id: 1, title: 'Application pack created', when: 'Today', detail: 'Fictional evidence claims selected for review' }, { id: 2, title: 'Readiness review started', when: 'Today', detail: 'Open gap and human review point are visible' }, { id: 3, title: 'Opportunity saved', when: 'Yesterday', detail: 'Aurora Relay added to the fictional workspace' }]), sources = ref([{ id: 'company', name: 'Fictional company careers', type: 'Company source', description: 'Illustrative direct employer source', enabled: true }, { id: 'referral', name: 'Fictional referral inbox', type: 'Lead source', description: 'Illustrative people-sourced opportunity notes', enabled: true }, { id: 'market', name: 'Fictional market watchlist', type: 'Watchlist', description: 'Illustrative companies to revisit', enabled: false }])
const materials = ref([{ name: 'Architecture portfolio.pdf', detail: 'Fictional evidence summary · no file exists or is uploaded', status: 'Ready to review' }, { name: 'Integration programme notes.docx', detail: 'Fictional work-history extract · no file exists or is uploaded', status: 'Ready to review' }, { name: 'Role preferences', detail: 'Fictional target-role and location criteria', status: 'Configured' }])
const materialsAnalyzed = ref(false), approvedRecommendations = ref([])
const recommendations = ['Prioritise platform architecture leadership roles', 'Use integration strategy as a supporting evidence theme', 'Keep EU remote and Netherlands hybrid as target preferences']
const selectedJob = computed(() => jobs.value.find(job => job.id === selectedId.value) || jobs.value[0])
const reviewJobs = computed(() => jobs.value.filter(job => job.status === 'new' || job.status === 'review'))
const activeApplications = computed(() => applications.value.filter(item => !item.stage.includes('later')))
const editableClaims = computed(() => selectedJob.value.pack.claims)
const readinessChecks = computed(() => [{ id: 'evidence', title: 'Evidence supports each selected claim', detail: 'Fictional evidence is visible in the pack.' }, { id: 'gap', title: 'Open gap has been reviewed', detail: selectedJob.value.gap }, { id: 'draft', title: 'Draft direction is clear', detail: 'A person can edit every part before use.' }])
const readinessScore = computed(() => Math.min(96, 62 + checkedReadiness.value.length * 11))
function go(id) { screen.value = id; menuOpen.value = false; toast.value = '' }
function selectJob(id) { selectedId.value = id; draftQuestion.value = jobs.value.find(job => job.id === id)?.pack.question || ''; draftSaved.value = false }
function statusLabel(status) { return ({ new: 'New', review: 'In review', apply: 'Preparing pack', saved: 'Saved', dismissed: 'Not now' })[status] || status }
function fitClass(score) { return score >= 80 ? 'strong' : score >= 70 ? 'promising' : 'review' }
function setDecision(job, decision) { job.status = decision; selectJob(job.id); if (decision === 'apply') { if (!applications.value.some(item => item.jobId === job.id)) applications.value.unshift({ jobId: job.id, stage: 'Draft in review', updated: 'Just now', next: 'Review evidence claims before sending' }); toast.value = `Application pack opened for ${job.company}.`; go('packs') } else { toast.value = `${job.company} marked “${statusLabel(decision)}” for this browser session.` } }
function saveDraft() { draftSaved.value = true; toast.value = 'Illustrative draft saved locally.' }
function resolveLead() { const note = leadDraft.value.trim(); const id = `cedar-${Date.now()}`; leads.value.unshift({ id, company: 'Cedar Systems', title: 'Technical Portfolio Lead', detail: note || 'Fictional manually captured lead · score explanation prepared', status: 'review' }); jobs.value.unshift({ id, company: 'Cedar Systems', title: 'Technical Portfolio Lead', location: 'Remote · EU', source: 'Fictional manual lead', score: 74, status: 'new', summary: 'Guide technical portfolios across platform and integration work.', signals: ['Architecture leadership', 'Integration planning', 'Delivery governance'], gap: 'Portfolio ownership should be clarified in a conversation.', salary: '€84k–€102k', pack: { title: 'Technical portfolio application outline', intro: 'Use fictional architecture and programme evidence, then review the role scope.', claims: ['Connected architecture choices to delivery planning.', 'Made cross-team dependencies visible and reviewable.', 'Balanced technical direction with programme governance.'], question: 'How is technical portfolio ownership shared across the organisation?' } }); leadDraft.value = ''; leadMessage.value = 'Fictional lead resolved locally and added to Top Jobs. No website was contacted.'; toast.value = 'A fictional lead is ready for review in Top Jobs.' }
function addActivity() { activity.value.unshift({ id: Date.now(), title: 'Human review noted', when: 'Just now', detail: 'Illustrative review event added only in this browser session' }); toast.value = 'Illustrative activity event added.' }
function analyzeMaterials() { materialsAnalyzed.value = true; approvedRecommendations.value = recommendations.slice(0, 2); toast.value = 'Fictional material analysis completed locally.' }
function jobFor(id) { return jobs.value.find(job => job.id === id) || jobs.value[0] }
function advanceApplication(application) { const stages = ['Draft in review', 'Ready for review', 'Prepared — not sent']; const index = stages.indexOf(application.stage); application.stage = stages[(index + 1) % stages.length]; application.updated = 'Just now'; application.next = application.stage === 'Prepared — not sent' ? 'A person must submit outside this demo' : 'Continue the human review'; toast.value = `${jobFor(application.jobId).company} moved to ${application.stage}.` }
function runScan() { if (scanning.value) return; scanning.value = true; window.setTimeout(() => { scanning.value = false; toast.value = 'Illustrative refresh complete: no network request was made.' }, 700) }
function resetDemo() { jobs.value = JSON.parse(JSON.stringify(originalJobs)); applications.value = JSON.parse(JSON.stringify(fixture.applications)); selectedId.value = 'aurora-platform'; checkedReadiness.value = ['evidence', 'gap']; enabledClaims.value = [0, 1, 2]; draftSaved.value = false; evidenceMessage.value = ''; toast.value = 'The fictional browser-session state has been reset.'; go('today') }
</script>

<style scoped>
.field-label { display: grid; gap: 7px; margin-top: 18px; color: #415964; font-size: .84rem; font-weight: 750; }
.field-label textarea, .compose input { width: 100%; resize: vertical; border: 1px solid #cbdade; border-radius: 7px; padding: 10px; color: #1c3440; line-height: 1.45; }
.simple-steps { display: grid; gap: 13px; padding-left: 20px; color: #50656e; font-size: .9rem; line-height: 1.4; }
.timeline { position: relative; margin: 18px 0 20px; padding-left: 22px; border-left: 2px solid #cce5de; }
.timeline article { position: relative; margin: 0 0 17px; }
.timeline i { position: absolute; left: -29px; top: 4px; width: 12px; height: 12px; border-radius: 50%; background: #20957f; }
.timeline strong, .timeline span { display: block; }
.timeline span { margin-top: 3px; color: #64767d; font-size: .8rem; }
.material-card { display: grid; grid-template-columns: 30px 1fr auto; gap: 9px; align-items: center; padding: 12px 0; border-bottom: 1px solid #e5ecee; }
.material-card > span { color: #397f94; font-size: 1.2rem; }
.material-card strong, .material-card small { display: block; }
.material-card small { margin-top: 3px; color: #64767d; font-size: .75rem; }
.material-card b { color: #16745c; font-size: .7rem; }
.recommendations { display: grid; gap: 9px; margin: 15px 0; }
</style>
