<template>
  <main class="demo-shell">
    <header class="hero" aria-labelledby="page-title">
      <p class="brand">ProofLine <span>·</span> interactive public demo</p>
      <h1 id="page-title">From evidence to a clearer application plan.</h1>
      <p class="hero-copy">{{ fixture.notice }} Nothing is uploaded, sent, saved, or generated by AI.</p>
    </header>

    <section class="notice" aria-label="Demo limitations">
      <strong>Illustrative only.</strong> This score is not a hiring prediction; it is a transparent example of a human-reviewed workflow.
    </section>

    <section class="card profile" aria-labelledby="profile-heading">
      <div>
        <p class="eyebrow">Fictional candidate profile</p>
        <h2 id="profile-heading">{{ fixture.candidate.displayName }}</h2>
        <p class="muted">{{ fixture.candidate.location }} · {{ fixture.candidate.headline }}</p>
        <p>{{ fixture.candidate.summary }}</p>
      </div>
      <ul class="strengths" aria-label="Illustrative strengths">
        <li v-for="strength in fixture.candidate.strengths" :key="strength">{{ strength }}</li>
      </ul>
    </section>

    <section class="card" aria-labelledby="vacancy-heading">
      <p class="eyebrow">1. Compare opportunities</p>
      <h2 id="vacancy-heading">Choose a fictional vacancy</h2>
      <div class="vacancy-grid">
        <button
          v-for="vacancy in fixture.vacancies"
          :key="vacancy.id"
          class="vacancy"
          :class="{ selected: vacancy.id === selected.id }"
          :aria-pressed="vacancy.id === selected.id"
          type="button"
          @click="selectVacancy(vacancy.id)"
        >
          <strong>{{ vacancy.title }}</strong>
          <span>{{ vacancy.company }} · {{ vacancy.workMode }}</span>
          <small>{{ vacancy.summary }}</small>
        </button>
      </div>
    </section>

    <section class="card score-grid" aria-labelledby="signals-heading">
      <div>
        <p class="eyebrow">2. Explore fit signals</p>
        <h2 id="signals-heading">{{ selected.company }} · {{ selected.title }}</h2>
        <p>{{ selected.summary }}</p>
        <fieldset>
          <legend>Turn illustrative evidence signals on or off</legend>
          <label v-for="signal in allSignals" :key="signal" class="toggle">
            <input v-model="enabledSignals" type="checkbox" :value="signal" />
            <span>{{ signalLabel(signal) }}</span>
          </label>
        </fieldset>
      </div>
      <aside class="score-panel" aria-live="polite" :aria-label="`Illustrative fit score: ${fitScore} out of 100`">
        <p class="eyebrow">Example score</p>
        <p class="score"><strong>{{ fitScore }}</strong><span>/100</span></p>
        <p class="score-label">{{ scoreLabel }}</p>
        <p class="formula">48 starting point + {{ matchingSignals }} matching signals × 14{{ architectureBonus ? ' + 5 architecture signal' : '' }}</p>
      </aside>
    </section>

    <section class="card plan" aria-labelledby="plan-heading">
      <p class="eyebrow">3. Simulate a reviewed plan</p>
      <h2 id="plan-heading">What the product can make easier</h2>
      <ol>
        <li :class="{ complete: planStep > 0 }">Match illustrative evidence to the role.</li>
        <li :class="{ complete: planStep > 1 }">Flag a conversation to have before applying: {{ selected.gap }}</li>
        <li :class="{ complete: planStep > 2 }">Prepare a human-reviewed application outline.</li>
      </ol>
      <button class="primary" type="button" @click="advancePlan">{{ planButtonLabel }}</button>
      <p v-if="planStep === 3" class="result" role="status">Illustrative direction: lead with {{ primarySignal }} evidence, then have a person review every claim before sending.</p>
    </section>
  </main>
</template>

<script setup>
import { computed, ref } from 'vue'
import fixture from './demo-data/proofline-public-demo.json'

const allSignals = ['platform', 'integration', 'leadership', 'architecture', 'product', 'delivery']
const selectedId = ref(fixture.vacancies[0].id)
const enabledSignals = ref(['platform', 'integration', 'leadership'])
const planStep = ref(0)
const selected = computed(() => fixture.vacancies.find((item) => item.id === selectedId.value) || fixture.vacancies[0])
const matchingSignals = computed(() => selected.value.signals.filter((signal) => enabledSignals.value.includes(signal)).length)
const architectureBonus = computed(() => enabledSignals.value.includes('architecture'))
const fitScore = computed(() => Math.min(96, 48 + matchingSignals.value * 14 + (architectureBonus.value ? 5 : 0)))
const scoreLabel = computed(() => fitScore.value >= 80 ? 'Strong fictional fit' : fitScore.value >= 65 ? 'Promising with review' : 'Explore the gaps')
const primarySignal = computed(() => selected.value.signals.find((signal) => enabledSignals.value.includes(signal)) || 'transferable')
const planButtonLabel = computed(() => ['Show evidence match', 'Show risk review', 'Show reviewed outline', 'Restart simulation'][planStep.value])

function signalLabel(signal) {
  return signal[0].toUpperCase() + signal.slice(1)
}

function selectVacancy(id) {
  selectedId.value = id
  planStep.value = 0
}

function advancePlan() {
  planStep.value = planStep.value === 3 ? 0 : planStep.value + 1
}
</script>

